
window.FACES_DATA = [
  {
    name: "Олег Луизо",
    gender: "мужской",
    age: 29,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1136424.jpg",
    education: "ГИТИС",
    hairColor: "Шатен",
    hairLength: "Средние",
    eyeColor: "Серо-голубой",
    height: 175,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1136424.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1136425.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1097052.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1097051.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1097048.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1097054.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u90119/video/2892044/2892044_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4134625/"
  },
  {
    name: "Данила Гульков",
    gender: "мужской",
    age: 25,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1010929.jpg",
    education: "ГИТИС",
    hairColor: "Русый",
    hairLength: "Средняя длина",
    eyeColor: "Серо-голубой",
    height: 180,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010929.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1049761.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1049760.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010930.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1010931.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u50220/video/2628467/2628467_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3309938/"
  },
  {
    name: "Анна Плаксина",
    gender: "женский",
    age: 23,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1110024.jpg",
    education: "ТИ им. Б. Щукина",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Синий",
    height: 185,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1110024.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1110042.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1110037.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1110038.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u64334/video/1816060/1816060.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3896607/"
  },
  {
    name: "Дарья Савичева",
    gender: "женский",
    age: 25,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1023853.jpg",
    education: "ГИТИС",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Зеленый",
    height: 167,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023853.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023849.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023857.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023856.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023854.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023852.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023851.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1023848.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u83185/video/2503887/2503887_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3164042/"
  },
 {
    name: "Дана Халифе",
    gender: "женский",
    age: 22,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1139111.jpg",
    education: "Московская школа кино",
    hairColor: "Русый",
    hairLength: "Длинные",
    eyeColor: "Каре-зеленый",
    height: 173,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139111.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139117.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139118.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139119.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u88274/video/3163373/3163373_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4181008/"
  },
  {
    name: "Артем Клименко",
    gender: "мужской",
    age: 33,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1032879.jpg",
    education: "ВТУ им. М.С. Щепкина",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Зеленый",
    height: 181,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032879.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032882.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032881.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032880.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032878.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1032877.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u11304/video/2547962/2547962_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3141461/"
  },
  {
    name: "Павел Федоров",
    gender: "мужской",
    age: 37,
    city: "Санкт-Петербург",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1082614.jpg",
    education: "СПбГИК",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-зеленый",
    height: 178,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082614.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082619.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082618.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082617.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082616.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1082615.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u19691/video/2793061/2793061_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3163630/"
  },
  {
    name: "Александра Шеина",
    gender: "женский",
    age: 27,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1150287.jpg",
    education: "ФШР",
    hairColor: "Шатен",
    hairLength: "Каре",
    eyeColor: "Серо-голубой",
    height: 166,
    bodyType: "Среднее",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150287.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150288.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150293.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150292.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150295.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150290.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150291.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1150289.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1029497.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u40154/video/3215123/3215123_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4057285/"
  },
 {
    name: "Александра Тамбовская",
    gender: "женский",
    age: 32,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1069483.jpg",
    education: "ТИ им. Б. Щукина",
    hairColor: "Блондин",
    hairLength: "Длинные",
    eyeColor: "Серо-голубой",
    height: 165,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1069483.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1012478.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1012484.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1012477.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1012476.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u81988/video/2436296/2436296_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4039962/"
  },
  {
    name: "Юрий Могила",
    gender: "мужской",
    age: 40,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1129267.jpg",
    education: "ГИТИС",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-зеленый",
    height: 170,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129274.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129271.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129270.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129267.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129258.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129256.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1129255.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/988885.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u37793/video/3053342/3053342_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3132479/"
  },
  {
    name: "Семен Моисеев",
    gender: "мужской",
    age: 26,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1098183.jpg",
    education: "РГИСИ",
    hairColor: "Русый",
    hairLength: "Средние",
    eyeColor: "Зеленый",
    height: 190,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1098183.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/572058.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1021581.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1021578.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1021577.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u62956/video/2577883/2577883_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3341790/"
  },
  {
    name: "Светлана Щуплова",
    gender: "женский",
    age: 23,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1139766.jpg",
    education: "ОГИИ им. Л. и М. Ростроповичей",
    hairColor: "Блондин",
    hairLength: "Длинные",
    eyeColor: "Серо-голубой",
    height: 167,
    bodyType: "Стройное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139766.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139769.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139768.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139765.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1139764.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u81992/video/3164635/3164635_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4040064/"
  },
  {
    name: "Богдан Карчевский",
    gender: "мужской",
    age: 19,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1076748.jpg",
    education: "ВТУ им. М.С. Щепкина",
    hairColor: "Русый",
    hairLength: "Короткие",
    eyeColor: "Серо-голубой",
    height: 180,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076748.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076757.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076763.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076758.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1076755.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u87833/video/2764033/2764033_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/4108095/"
  },
  {
    name: "Олег Щербаченко",
    gender: "мужской",
    age: 20,
    city: "Москва",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/1055216.jpg",
    education: "ВГИК",
    hairColor: "Шатен",
    hairLength: "Средние",
    eyeColor: "Черный",
    height: 191,
    bodyType: "Атлетичное",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055216.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055219.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055217.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055215.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055212.jpg",
      "https://trailers.filmtoolz.ru/images/photos_people/hq/1055211.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u66822/video/3167750/3167750_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3848212/"
  },
  {
    name: "Илья Марукович",
    gender: "мужской",
    age: 23,
    city: "Санкт-Петербург",
    photo: "https://trailers.filmtoolz.ru/images/photos_people/hq/932240.jpg",
    education: "СПбГИК",
    hairColor: "Русый",
    hairLength: "Средние",
    eyeColor: "Голубой",
    height: 170,
    bodyType: "Среднее",
    gallery: [
      "https://trailers.filmtoolz.ru/images/photos_people/hq/932240.jpg"
    ],
    video: "https://prefs.filmtoolz.ru/files/u55231/video/2030792/2030792_hd720p.mp4",
    filmtoolz: "https://casting.filmtoolz.ru/3955071/"
  }
];